import { notFound } from "next/navigation";
import { Wordmark } from "@/components/layout/Wordmark";
import type { Metadata } from "next";
import { prisma } from "@/lib/prisma";

interface ShareMeta {
  playerName?: string;
  teamName?: string;
  scopeLabel?: string;
  labels?: string[];
  keys?: string[];
}

async function loadReport(id: string) {
  const report = await prisma.report.findUnique({ where: { id } });
  if (!report) return null;
  return report;
}

export async function generateMetadata({
  params,
}: {
  params: { id: string };
}): Promise<Metadata> {
  const report = await loadReport(params.id);
  if (!report) return { title: "Report not found · SpikeLedger" };
  const meta = (report.metadata as unknown as ShareMeta) ?? {};
  const title = `${meta.playerName ?? "Player"} · ${meta.scopeLabel ?? "Report"}`;
  const description = `${meta.playerName ?? "Player"}'s performance report from ${
    meta.scopeLabel ?? "the season"
  }${meta.teamName ? ` - ${meta.teamName}` : ""}. Generated by SpikeLedger.`;
  return {
    title,
    description,
    openGraph: {
      title,
      description,
      images: [`/api/reports/${params.id}/og`],
      type: "article",
    },
    twitter: {
      card: "summary_large_image",
      title,
      description,
      images: [`/api/reports/${params.id}/og`],
    },
  };
}

export default async function SharePage({
  params,
}: {
  params: { id: string };
}) {
  const report = await loadReport(params.id);
  if (!report) notFound();
  const meta = (report.metadata as unknown as ShareMeta) ?? {};
  const labels = meta.labels ?? report.imageUrls.map((_, i) => `Image ${i + 1}`);

  return (
    <div className="min-h-screen bg-slate-50 text-slate-900">
      <div className="mx-auto max-w-3xl px-4 py-10 sm:px-6">
        <header className="text-center">
          <div className="inline-flex items-center gap-2 rounded-full border border-slate-200 bg-white/60 px-3 py-1 text-xs font-medium text-slate-700">
            <span className="h-1.5 w-1.5 rounded-full bg-emerald-600" />
            Match report
          </div>
          <h1 className="font-display text-3xl font-bold tracking-tight sm:text-4xl mt-4 text-slate-900">
            {meta.playerName ?? "Player report"}
          </h1>
          <p className="mt-1 text-sm text-slate-600">
            {meta.teamName ? `${meta.teamName} · ` : ""}
            {meta.scopeLabel ?? "Season"}
          </p>
        </header>

        <div className="mt-10 space-y-6">
          {report.imageUrls.map((url, i) => (
            <figure key={i} className="overflow-hidden rounded-lg border border-slate-200">
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img
                src={url}
                alt={labels[i] ?? `Image ${i + 1}`}
                className="block w-full"
              />
              <figcaption className="bg-white px-4 py-2 text-center text-xs text-slate-600">
                {labels[i] ?? `Image ${i + 1}`}
              </figcaption>
            </figure>
          ))}
        </div>

        <footer className="mt-14 border-t border-slate-200 pt-6 text-center text-sm text-slate-500">
          <div className="mb-3 flex justify-center">
            <Wordmark size="sm" />
          </div>
          <span className="font-medium text-slate-700">
            Powered by SpikeLedger
          </span>{" "}
          - free for coaches at{" "}
          <a
            href="/"
            className="text-orange-700 hover:text-orange-800"
          >
            spikeledger.app
          </a>
        </footer>
      </div>
    </div>
  );
}
