import type { Metadata, Viewport } from "next";
import { Barlow, Barlow_Condensed } from "next/font/google";
import { Analytics } from "@vercel/analytics/next";
import { SpeedInsights } from "@vercel/speed-insights/next";
import "./globals.css";
import { AuthProvider } from "@/components/providers/AuthProvider";
import { ServiceWorkerRegister } from "@/components/pwa/ServiceWorkerRegister";
import { OfflineIndicator } from "@/components/pwa/OfflineIndicator";

// Brand type. Barlow for reading, Barlow Condensed for headlines and
// scoreboard numbers. Self-hosted through next/font (no runtime request to
// Google) and exposed as CSS variables that tailwind.config.ts maps to
// `font-sans` and `font-display`.
const barlow = Barlow({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-barlow",
  display: "swap",
});

const barlowCondensed = Barlow_Condensed({
  subsets: ["latin"],
  weight: ["500", "600", "700", "800"],
  style: ["normal", "italic"],
  variable: "--font-barlow-condensed",
  display: "swap",
});

// iOS launch ("splash") images: brand background + centered wordmark, one per
// common iPhone resolution. Generated by scripts/generate-pwa-assets.mjs.
const APPLE_SPLASH: { url: string; media: string }[] = [
  ["750-1334", 375, 667, 2],
  ["828-1792", 414, 896, 2],
  ["1125-2436", 375, 812, 3],
  ["1242-2688", 414, 896, 3],
  ["1170-2532", 390, 844, 3],
  ["1284-2778", 428, 926, 3],
  ["1179-2556", 393, 852, 3],
  ["1290-2796", 430, 932, 3],
].map(([name, w, h, dpr]) => ({
  url: `/splash/apple-splash-${name}.png`,
  media: `screen and (device-width: ${w}px) and (device-height: ${h}px) and (-webkit-device-pixel-ratio: ${dpr}) and (orientation: portrait)`,
}));

export const metadata: Metadata = {
  title: "SpikeLedger - Volleyball stats that are fair to every position",
  description:
    "Courtside stat entry, the position-fair Bank Account, and report cards parents actually understand. Built by a club volleyball coach.",
  applicationName: "SpikeLedger",
  manifest: "/manifest.json",
  appleWebApp: {
    capable: true,
    title: "SpikeLedger",
    statusBarStyle: "default",
    startupImage: APPLE_SPLASH,
  },
};

export const viewport: Viewport = {
  themeColor: "#0b1a33",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${barlow.variable} ${barlowCondensed.variable}`}>
      <body className="min-h-screen bg-paper font-sans text-slate-900 antialiased">
        <OfflineIndicator />
        <AuthProvider>{children}</AuthProvider>
        <ServiceWorkerRegister />
        <Analytics />
        <SpeedInsights />
      </body>
    </html>
  );
}
