import type { Metadata, Viewport } from "next";
import "./globals.css";
import { AuthProvider } from "@/components/providers/AuthProvider";
import { ServiceWorkerRegister } from "@/components/pwa/ServiceWorkerRegister";
import { OfflineIndicator } from "@/components/pwa/OfflineIndicator";

// iOS launch ("splash") images: dark background + centered wordmark, one per
// common iPhone resolution. Generated by scripts/generate-pwa-assets.mjs.
const APPLE_SPLASH: { url: string; media: string }[] = [
  ["750-1334", 375, 667, 2],
  ["828-1792", 414, 896, 2],
  ["1125-2436", 375, 812, 3],
  ["1242-2688", 414, 896, 3],
  ["1170-2532", 390, 844, 3],
  ["1284-2778", 428, 926, 3],
  ["1179-2556", 393, 852, 3],
  ["1290-2796", 430, 932, 3],
].map(([name, w, h, dpr]) => ({
  url: `/splash/apple-splash-${name}.png`,
  media: `screen and (device-width: ${w}px) and (device-height: ${h}px) and (-webkit-device-pixel-ratio: ${dpr}) and (orientation: portrait)`,
}));

export const metadata: Metadata = {
  title: "SpikeLedger - Position-Fair Volleyball Analytics",
  description:
    "Turn match stats into coaching feedback you can use. The Bank Account system every volleyball coach needs.",
  applicationName: "SpikeLedger",
  manifest: "/manifest.json",
  appleWebApp: {
    capable: true,
    title: "SpikeLedger",
    statusBarStyle: "black-translucent",
    startupImage: APPLE_SPLASH,
  },
};

export const viewport: Viewport = {
  themeColor: "#cbf03c",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body className="min-h-screen bg-slate-950 text-slate-100 antialiased">
        <OfflineIndicator />
        <AuthProvider>{children}</AuthProvider>
        <ServiceWorkerRegister />
      </body>
    </html>
  );
}
