import { Bot } from "lucide-react";
import { cn } from "@/lib/utils";
import type { InsightProvider } from "@/engine/ai/types";

// Distinguish AI-authored content from rule-based fallback. The "rule-based"
// case still gets a badge so coaches know which engine produced what.
export function AIBadge({
  provider,
  cached,
  className,
}: {
  provider: InsightProvider;
  cached?: boolean;
  className?: string;
}) {
  if (provider === "rule-based") {
    return (
      <span
        className={cn(
          "inline-flex items-center gap-1 rounded border border-slate-200 bg-slate-100 px-2 py-0.5 font-display text-[11px] font-bold uppercase tracking-wider text-slate-600",
          className,
        )}
        title="Generated by the rule-based engine. Set ANTHROPIC_API_KEY for AI insights."
      >
        Standard
      </span>
    );
  }
  return (
    <span
      className={cn(
        "inline-flex items-center gap-1 rounded border border-navy-200 bg-navy-50 px-2 py-0.5 font-display text-[11px] font-bold uppercase tracking-wider text-navy-800",
        className,
      )}
      title={`AI-generated via ${provider}${cached ? " (cached)" : ""}`}
    >
      <Bot size={12} strokeWidth={2.25} aria-hidden />
      AI{cached ? " · cached" : ""}
    </span>
  );
}

export function AIUnavailableNote({ className }: { className?: string }) {
  return (
    <p className={cn("text-[11px] text-slate-500", className)}>
      AI insights unavailable - using standard analysis.
    </p>
  );
}
