import { cn } from "@/lib/utils";
import type { InsightProvider } from "@/engine/ai/types";

// Distinguish AI-authored content from rule-based fallback. The "rule-based"
// case still gets a badge so coaches know which engine produced what.
export function AIBadge({
  provider,
  cached,
  className,
}: {
  provider: InsightProvider;
  cached?: boolean;
  className?: string;
}) {
  if (provider === "rule-based") {
    return (
      <span
        className={cn(
          "inline-flex items-center gap-1 rounded-md border border-slate-700 bg-slate-800/60 px-2 py-0.5 text-[11px] font-semibold uppercase tracking-wide text-slate-400",
          className,
        )}
        title="Generated by the rule-based engine. Connect Ollama for AI insights."
      >
        Standard
      </span>
    );
  }
  return (
    <span
      className={cn(
        "inline-flex items-center gap-1 rounded-md border border-violet-400/40 bg-violet-400/10 px-2 py-0.5 text-[11px] font-semibold uppercase tracking-wide text-violet-200",
        className,
      )}
      title={`AI-generated via ${provider}${cached ? " (cached)" : ""}`}
    >
      <svg viewBox="0 0 24 24" fill="currentColor" className="h-3 w-3">
        <path d="M12 2l1.6 4.4L18 8l-4.4 1.6L12 14l-1.6-4.4L6 8l4.4-1.6z" />
      </svg>
      AI{cached ? " · cached" : ""}
    </span>
  );
}

export function AIUnavailableNote({ className }: { className?: string }) {
  return (
    <p className={cn("text-[11px] text-slate-500", className)}>
      AI insights unavailable - using standard analysis.
    </p>
  );
}
